services:
      App\BackOfficeBundle\Controller\UsersController:
            class: App\BackOfficeBundle\Controller\UsersController
            autowire: true
            tags: ['controller.service_arguments']
      App\BackOfficeBundle\Controller\AccountController:
            class: App\BackOfficeBundle\Controller\AccountController
            autowire: true
            tags: ['controller.service_arguments']
      App\BackOfficeBundle\Controller\LoginController:
            class: App\BackOfficeBundle\Controller\LoginController
            autowire: true
            tags: ['controller.service_arguments']

