app_backoffice_users:
    path:     /
    defaults: 
        _controller: AppBackOfficeBundle:Users:index
    methods: [GET]
    options:
        breadcrumb:
            label: USERS
            parent_route: app_backoffice_homepage
            
app_backoffice_users_add:
    path:     /new
    defaults: { _controller: AppBackOfficeBundle:Users:add }
    options:
        breadcrumb:
            label: ADD_USER
            parent_route: app_backoffice_users
    methods: [GET]

app_backoffice_users_landing:
    path:     /landing/{id}
    defaults: { _controller: AppBackOfficeBundle:Users:landing }
    methods: [GET]
    options:
        breadcrumb:
            label: USER
            parent_route: app_backoffice_users

app_backoffice_users_get:
    path:     /get/{id}
    defaults: { _controller: AppBackOfficeBundle:Users:get }
    methods: [GET]
    options:
        breadcrumb:
            label: USER
            parent_route: app_backoffice_users

app_backoffice_users_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBackOfficeBundle:Users:edit }
    methods: [GET]
    options:
        breadcrumb:
            label: EDIT_USER
            parent_route: app_backoffice_users

app_backoffice_users_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBackOfficeBundle:Users:delete }
    methods: [POST,DELETE]